### ISSUE TITLE
OGC filter strings

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/jsCSWwidget#1]
The wfs query isn't finding all WFS because it doesn't have wild cards. <PropertyIsLike> filters need include wildcard characters e.g. 

```
<ogc:And>
   <ogc:PropertyIsLike wildCard="*" singleChar="_" escape="/">
       <ogc:PropertyName>subject</ogc:PropertyName>
       <ogc:Literal>*wfs*</ogc:Literal>
   </ogc:PropertyIsLike>
   <ogc:PropertyIsLike wildCard="*" singleChar="_" escape="/">
       <ogc:PropertyName>AnyText</ogc:PropertyName>
       <ogc:Literal>*temperature*</ogc:Literal>
   </ogc:PropertyIsLike>
</ogc:And>
```

**Comment by wushengcq** [comment]
I have add the wildcard characters to the request filter, and fixed several bugs in IE  :- )

**Comment by smrgeoinfo** [comment]
I was testing again today and the filter strings still don't look correct:
here's the widget window:
![widget with search for AnyText contains 'heat' and 'wms'](https://cloud.githubusercontent.com/assets/513380/8214439/145b0fa2-14de-11e5-89b7-3f0189150072.png)

here's the ogc:filter in the request that gets sent when clicking 'Find':

```
<ogc:Filter xmlns:ogc='http://www.opengis.net/ogc' xmlns:gml='http://www.opengis.net/gml'>
<ogc:And>
<ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
<ogc:PropertyName>subject</ogc:PropertyName>
<ogc:Literal>%wms%</ogc:Literal>
</ogc:PropertyIsLike>
<ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
<ogc:PropertyName>AnyText</ogc:PropertyName>
<ogc:Literal>heat wms</ogc:Literal>
</ogc:PropertyIsLike>
</ogc:And>
</ogc:Filter>
```

the literal for AnyText should be %heat%

[interesting side bar-- when I run the request with 'heat wms' for any text with the widget I get 98 hits, when I run it as a POST using 'Advanced Rest Client', I get 152 hits.

**Comment by wushengcq** [comment]
I have do some test to compare the responses came back from http://catalog.usgin.org/geothermal/csw
- AnyText LIKE %heat% AND AnyText LIKE %wms%  
  **(get 4 hits)**

```
<ogc:Filter xmlns:ogc='http://www.opengis.net/ogc' xmlns:gml='http://www.opengis.net/gml'>
    <ogc:And>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>AnyText</ogc:PropertyName><ogc:Literal>%heat%</ogc:Literal>
        </ogc:PropertyIsLike>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>AnyText</ogc:PropertyName><ogc:Literal>%wms%</ogc:Literal>
        </ogc:PropertyIsLike>
    </ogc:And>
</ogc:Filter>
```
- AnyText LIKE heat AND AnyText LIKE wms <br/>
  **(without wildCard %, get 4 hits)** 

```
<ogc:Filter xmlns:ogc='http://www.opengis.net/ogc' xmlns:gml='http://www.opengis.net/gml'>
    <ogc:And>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>AnyText</ogc:PropertyName><ogc:Literal>heat</ogc:Literal>
        </ogc:PropertyIsLike>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>AnyText</ogc:PropertyName><ogc:Literal>wms</ogc:Literal>
        </ogc:PropertyIsLike>
    </ogc:And>
</ogc:Filter>
```
- AnyText LIKE heat wms <br/>
  **(let server to handle the search keys, get 2987 hits)** 

```
<ogc:Filter xmlns:ogc='http://www.opengis.net/ogc' xmlns:gml='http://www.opengis.net/gml'>
    <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
        <ogc:PropertyName>AnyText</ogc:PropertyName><ogc:Literal>heat wms</ogc:Literal>
    </ogc:PropertyIsLike>
</ogc:Filter>
```
- AnyText LIKE heat wms AND subject LIKE wms <br/>
  **(record's subject must include wms, get 81 hits)** 

```
<ogc:Filter xmlns:ogc='http://www.opengis.net/ogc' xmlns:gml='http://www.opengis.net/gml'>
    <ogc:And>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>subject</ogc:PropertyName>
            <ogc:Literal>wms</ogc:Literal>
        </ogc:PropertyIsLike>
        <ogc:PropertyIsLike wildCard='%' singleChar='_' escape='\'>
            <ogc:PropertyName>AnyText</ogc:PropertyName>
            <ogc:Literal>heat wms</ogc:Literal>
        </ogc:PropertyIsLike>
    </ogc:And>
</ogc:Filter>
```

**Comment by jessicagood** [comment]
In the current live build of this [app](http://polar.geodacenter.org/jsCSWwidget/test/ui-test.htm) if we do a search for `arizona` with wms checked we get 81 results. If we do a search of `gobbeldygook` we get 81 results. This is because `wms` was being added as a search [here](https://github.com/usgin/jsCSWwidget/blob/2181b703489ac8662ebc83406e9604459a937583/lib/jsCSWwidget/js/widget.js#L487). 

When two search terms are used, as with `arizona wms`, the CSW defaults to searching for `arizona` OR `wms`. So I commented out the line above and the one for wfs. The terms wms and wfs are already being added when building the [buildFilter function](https://github.com/usgin/jsCSWwidget/blob/2181b703489ac8662ebc83406e9604459a937583/lib/jsCSWwidget/js/csw.js#L97) so that is all we need. 

Now searching for `arizona` with wms checked we get 11 results and a search for `gobbeldygook` yields 0 results.

I also added a hint for the user in the UI so they know to add `AND` if they are using multiple search terms and want and inclusive search.

I think any other problems with return results is because of catalog/metadata issues, not the search function.
